/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './string-format.module';
export const StringFormatModuleNgFactory:i0.NgModuleFactory<i1.StringFormatModule> = i0.ɵcmf(i1.StringFormatModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.StringFormatModule,i1.StringFormatModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya3NwYWNlL25neC1zdHJpbmdmb3JtYXQvc3JjL2FwcC9zdHJpbmctZm9ybWF0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3Jrc3BhY2Uvbmd4LXN0cmluZ2Zvcm1hdC9zcmMvYXBwL3N0cmluZy1mb3JtYXQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7In0=
